export const TYPES = {
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ONE_FROM_CART : "REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART : "REMOVE_ALL_FROM_CART",
    CLEAR_CART: 'CLEAR_CART',
    CALCULATE_TOTAL: 'CALCULATE_TOTAL',
    SET_PRODUCTS:"SET_PRODUCTS",
    SET_LOADING:"SET_LOADING"
}

